[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "notion-client>=2.4.0",
    "pillow>=11.3.0",
    "reportlab>=4.4.3",
    "requests>=2.32.4",
]
